"""Add current_stage to workflows

Revision ID: cf5eebc3639a
Revises: f7c7ae8bfdcd
Create Date: 2026-01-13 23:47:15.227576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5eebc3639a'
down_revision: Union[str, Sequence[str], None] = 'f7c7ae8bfdcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('current_stage', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'current_stage')
    # ### end Alembic commands ###
