"""Initial schema

Revision ID: f7c7ae8bfdcd
Revises: 
Create Date: 2026-01-09 19:50:37.483779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c7ae8bfdcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('affiliation', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('total_workflows', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('inclusion_criteria', sa.Text(), nullable=True),
    sa.Column('exclusion_criteria', sa.Text(), nullable=True),
    sa.Column('databases', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('papers_found', sa.Integer(), nullable=True),
    sa.Column('papers_screened', sa.Integer(), nullable=True),
    sa.Column('papers_included', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manuscripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('methods', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.Column('conclusions', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('figures', sa.JSON(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_table('papers',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('pmcid', sa.String(length=20), nullable=True),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True),
    sa.Column('s2_id', sa.String(length=50), nullable=True),
    sa.Column('openalex_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('mesh_terms', sa.JSON(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('full_text_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('text_extraction_method', sa.String(length=20), nullable=True),
    sa.Column('text_quality_score', sa.Float(), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('pdf_file_path', sa.String(length=1000), nullable=True),
    sa.Column('open_access', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_pmcid'), 'papers', ['pmcid'], unique=False)
    op.create_index(op.f('ix_papers_pmid'), 'papers', ['pmid'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=100), nullable=False),
    sa.Column('schema_name', sa.String(length=50), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('extraction_quality', sa.Float(), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=True),
    sa.Column('conflicts', sa.JSON(), nullable=True),
    sa.Column('reviewer_decisions', sa.JSON(), nullable=True),
    sa.Column('low_confidence_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('matched_inclusion', sa.JSON(), nullable=True),
    sa.Column('matched_exclusion', sa.JSON(), nullable=True),
    sa.Column('is_conflict', sa.Boolean(), nullable=True),
    sa.Column('second_opinion', sa.JSON(), nullable=True),
    sa.Column('human_reviewed', sa.Boolean(), nullable=True),
    sa.Column('ai_decision', sa.String(length=20), nullable=True),
    sa.Column('human_decision', sa.String(length=20), nullable=True),
    sa.Column('overridden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_decisions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_papers_pmid'), table_name='papers')
    op.drop_index(op.f('ix_papers_pmcid'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_table('manuscripts')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
